language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run build

deploy:
  local-dir: dist/team-work-work-flow
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
