language: node_js
node_js:
  - "12"
before_script:
  - npm install
script:
  - yarn build
deploy:
  local-dir: dist/teamWorkWorkFlow
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
